% Returns the ETable Options to Load Data for this Lab Given the String 
% 'xunits' which is the units used by "x" for the experiment type (SI base 
% units, so "rad" for torsional and "m" for rectilinear).
function options = ETOptions(xunits)
    options = struct(...
        'isText', true, ...
        'ignoreLines', 21, ...
        ... % Variable Names for Each Column:
        'shortNames', ["t","F", "x1","x2","x3", "E", "v1","v2","v3", "a1","a2","a3", "note"], ...
        ... % Latex formated units for each column:
        'unitsList', ["s","N", xunits,xunits,xunits, "", "$\tfrac{"+xunits+"}{s}$","$\tfrac{"+xunits+"}{s}$","$\tfrac{"+xunits+"}{s}$", "$\tfrac{"+xunits+"}{s^2}$","$\tfrac{"+xunits+"}{s^2}$","$\tfrac{"+xunits+"}{s^2}$", ""] ...
    );
end